language: node_js
node_js:
  - "node"
sudo: false
dist: trusty
# services:
#   - postgresql
addons:
  postgresql: "9.6"
before_install:
  - psql -c 'create database test;' -U postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
    - NODE_ENV=TEST
