language: node_js
node_js:
  - "node"
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/codeface
    - NODE_ENV=TEST
services:
  - postgresql
# before_install:
#   - psql -U postgres -c 'CREATE DATABASE codeface;'
after_success:
  - bash <(curl -s https://codecov.io/bash)
