language: node_js
node_js:
  - "node"
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/codeface
    - NODE_ENV=TEST
services:
  - postgresql
before_install:
  - psql -c 'create database codeface;' -U postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)
